INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,23);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,29);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,19);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,7);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,35);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,11);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,39);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,43);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,47);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,53);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,15);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,25);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,91);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,83);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,87);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (7,89);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,1);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,3);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,17);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,11);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,13);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,25);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,49);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,7);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,47);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,19);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,31);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,45);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,79);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,67);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,65);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,53);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,41);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,97);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,99);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (6,71);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,17);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,9);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,5);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,45);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,25);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,21);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,15);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,29);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,37);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,41);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,51);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,83);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,87);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,95);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (5,97);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,1);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,5);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,3);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,11);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,15);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,23);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,35);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,47);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,53);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,49);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,57);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,59);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,65);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,69);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,73);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,79);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,81);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,85);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,1);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,5);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,7);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,9);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,11);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,15);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,21);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,23);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,29);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,35);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,37);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,39);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,45);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,47);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,49);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,51);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,59);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,65);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,79);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,67);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,71);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,81);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,85);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,89);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,95);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (3,99);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,5);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,9);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,17);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,21);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,39);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,45);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,61);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,67);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,69);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,81);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,85);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,91);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,93);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,89);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,87);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,95);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (2,99);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,33);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,11);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,45);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,63);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,67);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,73);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,79);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,7);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,19);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,85);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,91);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,87);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,91);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,95);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (4,99);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 19);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 27);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 35);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 41);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 47);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 55);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 59);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 61);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 65);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 77);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 61);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 71);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 79);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 81);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 85);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 97);
INSERT INTO PersonHobby (HobbyId,PersonId) VALUES (1, 99);